### PR TITLE
Redmine 5.0.0 compatibility

### PR DESCRIPTION
**Pull request by rrsach**
Fixed Autoloading for Redmine 5.0 - This probably does not work with older Redmine Versions so it must be either in a separated branch or fixed by someone who actually can code ruby 😄 

But maybe this is helpful for others if you want to get it running with Redmine 5.

### CODE REVIEW

**Comment by ashrafalzyoud** [comment]
Are u test it without any problems?!!

**Comment by ashrafalzyoud** [comment]
redmine@172:~/5.0$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NameError: uninitialized constant PLUGIN_MIGRATION_CLASS
/home/redmine/5.0/plugins/computed_custom_field/db/migrate/20161229192026_add_custom_fields_formula.rb:1:in `<top (required)>'
/home/redmine/5.0/lib/redmine/plugin.rb:468:in `up'
/home/redmine/5.0/lib/redmine/plugin.rb:500:in `migrate_plugin'
/home/redmine/5.0/lib/redmine/plugin.rb:441:in `migrate'
/home/redmine/5.0/lib/redmine/plugin.rb:455:in `block in migrate'
/home/redmine/5.0/lib/redmine/plugin.rb:454:in `each'
/home/redmine/5.0/lib/redmine/plugin.rb:454:in `migrate'
/home/redmine/5.0/lib/tasks/redmine.rake:151:in `block (3 levels) in <top (required)>'
/home/redmine/.rbenv/versions/3.0.3/bin/bundle:23:in `load'
/home/redmine/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'

Caused by:
NameError: uninitialized constant PLUGIN_MIGRATION_CLASS
/home/redmine/5.0/plugins/computed_custom_field/db/migrate/20161229192026_add_custom_fields_formula.rb:1:in `<top (required)>'
/home/redmine/5.0/lib/redmine/plugin.rb:468:in `up'
/home/redmine/5.0/lib/redmine/plugin.rb:500:in `migrate_plugin'
/home/redmine/5.0/lib/redmine/plugin.rb:441:in `migrate'
/home/redmine/5.0/lib/redmine/plugin.rb:455:in `block in migrate'
/home/redmine/5.0/lib/redmine/plugin.rb:454:in `each'
/home/redmine/5.0/lib/redmine/plugin.rb:454:in `migrate'
/home/redmine/5.0/lib/tasks/redmine.rake:151:in `block (3 levels) in <top (required)>'
/home/redmine/.rbenv/versions/3.0.3/bin/bundle:23:in `load'
/home/redmine/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by ashrafalzyoud** [comment]
@rrsach 
@dpalic

**Comment by ldupuy-insa** [comment]
Hello,
I'm having the same problem as @ashrafalzyoud, but I'm so excited to use this plugin with the v5.
Thank you very much for this work achieved about this functionalities :-).

**Comment by ashrafalzyoud** [comment]
@dpalic @rrsach @ldupuy-insa 
We need it's in redmine5

**Review by rizvitafseer — APPROVED** [review]

**Comment by ashrafalzyoud** [comment]
@rrsach any update?

**Comment by rrsach** [comment]
@ashrafalzyoud The plugin works fine for me, so I cannot really help. Try migrating with 5.0.0 as I did this with this version.

**Comment by ldupuy-insa** [comment]
@rrsach I use Redmine v5 and to make it work, I just modified `class AddCustomFieldsIsComputed < PLUGIN_MIGRATION_CLASS` by `class AddCustomFieldsIsComputed < ActiveRecord::Migration[4.2]` in these files :
-  db/migrate/20161229192026_add_custom_fields_formula.rb
- db/migrate/20161229192027_add_custom_fields_is_computed.rb
- db/migrate/20170205204732_convert_custom_fields.rb

But I'm not a Ruby Redmine Developer and I don't know if it is in the best practices =s.

**Comment by rrsach** [comment]
@ldupuy-insa 

Thanks! I am not a ruby developer either, that is a bit the problem 😉  If anyone could quickly review this and verify it works (as I have already migrated, I cannot test it) and you could do a pull request I could put it in my fork and might have it merged in here at some point

**Comment by dpalic** [comment]
right now not having the time to test it, is someone able to test it? I will release it afterwards, but require support on maintaining if it fails

**Comment by lavy0511** [comment]
@rrsach 
Validate the suggested settings in my redmine 5.0.1, but it doesn't start redmine. Did it work for someone?.  I am not a ruby developer either

**Comment by Bonerserk** [comment]
It doesn't work with 5.0.4 Redmine version.
I also try solution proposed by @ldupuy-insa but without result.

**Comment by JGallot** [comment]
Hello,
The solution by  @ldupuy-insa works well on redmine 5.0.5

**Comment by ilyacherevkov** [comment]
For 5.0.5 I 

1) deleted lib/computed_custom_field/computed_custom_field.rb
2) modified migrations to use ` ActiveRecord::Migration[4.2]` instead of `PLUGIN_MIGRATION_CLASS`
3) modified init.rb

init.rb
```
require 'redmine'

require_relative 'lib/computed_custom_field/custom_field_patch'
require_relative 'lib/computed_custom_field/custom_fields_helper_patch'
require_relative 'lib/computed_custom_field/model_patch'
require_relative 'lib/computed_custom_field/issue_patch'
require_relative 'lib/computed_custom_field/hooks'

Redmine::Plugin.register :computed_custom_field do
  name 'Computed custom field'
  author 'Yakov Annikov'
  url 'https://github.com/annikoff/redmine_plugin_computed_custom_field'
  description ''
  version '1.0.7'
  settings default: {}
end

RedmineApp::Application.configure do
  config.after_initialize do
    models = [
      Enumeration, Group, Issue, Project,
      TimeEntry, User, Version
    ]
    models.each do |model|
      if model.included_modules
              .exclude?(ComputedCustomField::ModelPatch)
        model.send :include, ComputedCustomField::ModelPatch
      end
    end
  end
end
```

and it seems to work.

**Comment by gcornacchia** [comment]
hi @dpalic any news on redmine 5.x compatibility plugin availability?

**Pull request merged**
